CREATE PROCEDURE SP_SM_ROLE_INSERT
@NAME NVARCHAR(200),
@IS_ACTIVE INT
AS
BEGIN
	INSERT INTO HMS_SM_ROLE(NAME, IS_ACTIVE)
	VALUES
	(@NAME, @IS_ACTIVE)
END

EXEC SP_SM_ROLE_INSERT 'Branch Manager [BM]', 1
