CREATE PROCEDURE SP_SM_MODULE_INSERT
@NAME NVARCHAR(200),
@MODULE_KEY NVARCHAR(200),
@POSITION INT, 
@ICON NVARCHAR(200),
@DESCRIPTION NVARCHAR(MAX),
@IS_ACTIVE INT
AS
BEGIN
	INSERT INTO HMS_SM_MODULE (NAME, MODULE_KEY, POSITION, ICON, DESCRIPTION, IS_ACTIVE)
	VALUES
	(
		@NAME, @MODULE_KEY, @POSITION, @ICON, @DESCRIPTION, @IS_ACTIVE
	)
END

EXEC SP_SM_MODULE_INSERT 'Patient', 'PATIENT', 2, 'fa fa-user', 'Doctor Module', 1
