CREATE PROCEDURE SP_SM_MODULE_TABLE_INSERT
@MODULE_ID INT,
@TABLE_NAME NVARCHAR(200),
@STATUS INT
AS
BEGIN
	INSERT INTO HMS_SM_MODULE_TABLE (MODULE_ID, TABLE_NAME, STATUS)
	VALUES
	(@MODULE_ID, @TABLE_NAME, @STATUS);
END
