ALTER PROCEDURE SP_SM_PERMISSION_INSERT
@DISPLAY_NAME NVARCHAR(200),
@MODULE_ID INT,
@IS_TOPBAR INT,
@PARENT_ID INT,
@IS_ACTIVE INT
AS
BEGIN
	INSERT INTO HMS_SM_PERMISSION (DISPLAY_NAME, PERMISSION_KEY, MODULE_ID, IS_ACTIVE, IS_TOPBAR, PARENT_ID)
	VALUES
	(
		@DISPLAY_NAME, REPLACE(UPPER(@DISPLAY_NAME), ' ', '_'), @MODULE_ID, @IS_ACTIVE, @IS_TOPBAR, @PARENT_ID
	)
END

EXEC SP_SM_PERMISSION_INSERT 'System Data',1,1,NULL,1


EXEC SP_SM_PERMISSION_INSERT 'Branch Manage',1,1,NULL,1
EXEC SP_SM_PERMISSION_INSERT 'Create Branch',1,1,1031,1
EXEC SP_SM_PERMISSION_INSERT 'Edit Branch',1,1,1031,1
EXEC SP_SM_PERMISSION_INSERT 'Delete Branch',1,1,1031,1
EXEC SP_SM_PERMISSION_INSERT 'Branch DB Access',1,1,1031,1




SELECT * FROM HMS_SM_PERMISSION
	















