ALTER PROCEDURE SP_SM_PERMISSION_INSERT
@DISPLAY_NAME NVARCHAR(200),
@MODULE_ID INT,
@IS_TOPBAR INT,
@PARENT_ID INT,
@IS_ACTIVE INT
AS
BEGIN
	INSERT INTO HMS_SM_PERMISSION (DISPLAY_NAME, PERMISSION_KEY, MODULE_ID, IS_ACTIVE, IS_TOPBAR, PARENT_ID)
	VALUES
	(
		@DISPLAY_NAME, REPLACE(UPPER(@DISPLAY_NAME), ' ', '_'), @MODULE_ID, @IS_ACTIVE, @IS_TOPBAR, @PARENT_ID
	)
END

EXEC SP_SM_PERMISSION_INSERT 'System Data',1,1,NULL,1


EXEC SP_SM_PERMISSION_INSERT 'Branch Manage',1,1,NULL,1
EXEC SP_SM_PERMISSION_INSERT 'Create Branch',1,1,1031,1
EXEC SP_SM_PERMISSION_INSERT 'Edit Branch',1,1,1031,1
EXEC SP_SM_PERMISSION_INSERT 'Delete Branch',1,1,1031,1
EXEC SP_SM_PERMISSION_INSERT 'Branch DB Access',1,1,1031,1


EXEC SP_SM_PERMISSION_INSERT 'Security Manager', 1, NULL, NULL, 1
EXEC SP_SM_PERMISSION_INSERT 'Role', 1, 1, NULL, 1
EXEC SP_SM_PERMISSION_INSERT 'Create Role', 1, 1, 1046, 1
EXEC SP_SM_PERMISSION_INSERT 'Edit Role', 1, 1, 1046, 1
EXEC SP_SM_PERMISSION_INSERT 'Delete Role', 1, 1, 1046, 1

EXEC SP_SM_PERMISSION_INSERT 'User', 1, 1, NULL, 1
EXEC SP_SM_PERMISSION_INSERT 'Create Role', 1, 1, 1050, 1
EXEC SP_SM_PERMISSION_INSERT 'Edit Role', 1, 1, 1050, 1
EXEC SP_SM_PERMISSION_INSERT 'Delete Role', 1, 1, 1050, 1

EXEC SP_SM_PERMISSION_INSERT 'Branch Manage',1,1,NULL,1
EXEC SP_SM_PERMISSION_INSERT 'Create Branch',1,1,1054,1
EXEC SP_SM_PERMISSION_INSERT 'Edit Branch',1,1,1054,1
EXEC SP_SM_PERMISSION_INSERT 'Delete Branch',1,1,1054,1
EXEC SP_SM_PERMISSION_INSERT 'Branch DB Access',1,1,1054,1



EXEC SP_SM_PERMISSION_INSERT 'System Data', 2, NULL, NULL, 1
EXEC SP_SM_PERMISSION_INSERT 'Department', 2, 1, NULL, 1
EXEC SP_SM_PERMISSION_INSERT 'Create Department', 2, 1, 1060, 1
EXEC SP_SM_PERMISSION_INSERT 'Edit Department', 2, 1, 1060, 1
EXEC SP_SM_PERMISSION_INSERT 'Delete Department', 2, 1, 1060, 1

EXEC SP_SM_PERMISSION_INSERT 'Blood Group', 2, 1, NULL, 1
EXEC SP_SM_PERMISSION_INSERT 'Create Blood Group', 2, 1, 1064, 1
EXEC SP_SM_PERMISSION_INSERT 'Edit Blood Group', 2, 1, 1064, 1
EXEC SP_SM_PERMISSION_INSERT 'Delete Blood Group', 2, 1, 1064, 1

EXEC SP_SM_PERMISSION_INSERT 'Designation',2,1,NULL,1
EXEC SP_SM_PERMISSION_INSERT 'Create Designation',2,1,1068,1
EXEC SP_SM_PERMISSION_INSERT 'Edit Designation',2,1,1068,1
EXEC SP_SM_PERMISSION_INSERT 'Delete Designation',2,1,1068,1


UPDATE HMS_SM_PERMISSION
SET MODULE_ID=2 WHERE ID IN (1065,1066,1067)


SELECT * FROM HMS_SM_MODULE
SELECT * FROM HMS_SM_PERMISSION






SELECT * FROM HMS_SM_PERMISSION
	















