CREATE PROCEDURE SP_SM_PERMISSION_INSERT
@DISPLAY_NAME NVARCHAR(200),
@MODULE_ID INT
AS
BEGIN
	INSERT INTO HMS_SM_PERMISSION (DISPLAY_NAME, PERMISSION_KEY, MODULE_ID, IS_ACTIVE)
	VALUES
	(
		@DISPLAY_NAME, REPLACE(UPPER(@DISPLAY_NAME), ' ', '_'), @MODULE_ID, 1
	)
END

EXEC SP_SM_PERMISSION_INSERT '--Add Branch',1


SELECT * FROM HMS_SM_MODULE
	


SELECT * FROM HMS_SM_PERMISSION