CREATE PROCEDURE SP_SM_USER_INSERT
@DISPLAY_NUMBER NVARCHAR(50),
@FIRST_NAME NVARCHAR(200),
@LAST_NAME NVARCHAR(200),
@FULL_NAME NVARCHAR(200),
@EMAIL NVARCHAR(200),
@CONTACT_NO NVARCHAR(50),
@ROLE_ID INT,
@DESIGNATION_ID INT,
@BRANCH_ID INT,
@IS_ACTIVE INT,
@STATUS NVARCHAR(50),
@USER_NAME NVARCHAR(50),
@PASSWORD NVARCHAR(MAX),
@IS_TEMP_PASSWORD INT,
@UPDATED_AT DATETIME,
@UPDATED_BY INT
AS
BEGIN
	INSERT INTO HMS_SM_USER
	(DISPLAY_NUMBER,FIRST_NAME, LAST_NAME, FULL_NAME, EMAIL, CONTACT_NO, ROLE_ID, DESIGNATION_ID, BRANCH_ID, IS_ACTIVE, STATUS, USER_NAME, PASSWORD, IS_TEMP_PASSWORD, UPDATED_AT, UPDATED_BY)
	VALUES
	(@DISPLAY_NUMBER,@FIRST_NAME, @LAST_NAME, @FULL_NAME, @EMAIL, @CONTACT_NO,@ROLE_ID,@DESIGNATION_ID,@BRANCH_ID,@IS_ACTIVE,@STATUS,@USER_NAME,@PASSWORD,@IS_TEMP_PASSWORD,@UPDATED_AT,@UPDATED_BY)
END