CREATE PROCEDURE SP_SD_DEPARTMENT_GET_BY_ID
@ID INT
AS
BEGIN
	SELECT NAME, SHORT_NAME, DEPARTMENT_ICON,
	CASE
		WHEN STATUS = 1 THEN 'Active'
		WHEN STATUS = 0 THEN 'Inactive'
	END AS STATUS
	FROM HMS_SD_DEPARTMENTS
	WHERE ID = @ID
END

EXEC SP_SD_DEPARTMENT_GET_BY_ID 1053