CREATE PROCEDURE SP_SD_DEPARTMENT_UPDATE
@ID INT,
@NAME NVARCHAR(200),
@SHORT_NAME NVARCHAR(200),
@STATUS INT
AS
BEGIN
	UPDATE HMS_SD_DEPARTMENTS SET 
		NAME = @NAME,
		SHORT_NAME = @SHORT_NAME,
		STATUS = @STATUS
	WHERE ID = @ID
END
