CREATE PROCEDURE SP_SD_CREATE_DEPARTMENT  
@NAME NVARCHAR(100),  
@SHORT_NAME NVARCHAR(100),  
@DEPARTMENT_ICON NVARCHAR(2000),  
@STATUS INT  
  
AS  
BEGIN  
 SET NOCOUNT ON;  
 INSERT INTO HMS_SD_DEPARTMENTS (NAME,SHORT_NAME,DEPARTMENT_ICON,STATUS)  
 VALUES (@NAME, @SHORT_NAME, @DEPARTMENT_ICON, @STATUS)  
END